spring:
  cloud:
    discovery:
      enabled: false
    httpclientfactories:
      apache:
        enabled: false
      ok:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - configprops
          - refresh

togglz:
  console:
    enabled: false
